# Generated by Django 3.2.23 on 2023-12-05 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('invoice_number', models.IntegerField(unique=True)),
                ('customer_name', models.CharField(max_length=30)),
                ('billing_address', models.CharField(max_length=30)),
                ('shipping_address', models.CharField(max_length=30)),
                ('gstin', models.CharField(max_length=30)),
                ('total_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('quantity', models.FloatField()),
                ('amount', models.FloatField()),
                ('invoice_header', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.invoiceheader')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceBillSundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_sundry_name', models.CharField(max_length=30)),
                ('amount', models.FloatField()),
                ('type_of_operation', models.CharField(default='s', max_length=1)),
                ('invoice_header', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.invoiceheader')),
            ],
        ),
    ]
