# Generated by Django 3.2.23 on 2023-12-05 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicebillsundry',
            name='invoice_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.invoiceheader'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.invoiceheader'),
        ),
    ]
