# Generated by Django 3.2.23 on 2023-12-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20231206_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
